CovidForm/CovidForm/Models/Shared/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ModelView;
using System.Web.Mvc;

namespace CovidForm.Models.Shared
{
    public class Message
    {
        public string PropertyName { get; set; }
        public string PropertyValue { get; set; }

        public static List<Message> GetMessageErrorByModel(
            string modelName, ModelStateDictionary modelData)
        {
            List<Message> listError = new List<Message>();

            List<Message> listErrorByModel = GetMessageError(modelName, modelData);

            List<string> listFieldClass = typeof(Covid_ModelView).GetProperties().Select(a => a.Name).ToList();

            foreach (var field in listFieldClass)
            {
                int index = listErrorByModel.FindIndex(n => n.PropertyName == field);

                Message message = new Message();
                message.PropertyName = field;

                if (index >= 0)
                {
                    message.PropertyValue = listErrorByModel[index].PropertyValue;
                }
                else { message.PropertyValue = string.Empty; }
                listError.Add(message);
            }
            return listError;
        }

        static List<Message> GetMessageError(string modelName,
            ModelStateDictionary modelData)
        {
            List<Message> listError = new List<Message>();
            foreach (KeyValuePair<string, ModelState>
                ms in modelData)
            {
                ModelState modelState = ms.Value;
                Message message = new Message();
                message.PropertyName =
                    GetFieldNameByObject(modelName + ".", ms.Key);

                if (modelState.Errors.Count > 0)
                {
                    message.PropertyValue =
                   string.Join("\n", GetErrorMessageByField(modelState));
                }
                else
                {
                    message.PropertyValue = string.Empty;
                }
                listError.Add(message);
            }
            return listError;
        }

        private static List<string> GetErrorMessageByField(
            ModelState modelState)
        {
            List<string> listError = new List<string>();
            foreach (ModelError error in modelState.Errors)
            {
                listError.Add(error.ErrorMessage);
            }

            return listError;
        }

        private static string GetFieldNameByObject(string v,
            string key)
        {
            if (key.Contains(v))
            {
                key = key.Replace(v, "");
            }
            return key;
        }
    }
}

CovidForm/CovidForm/Controllers/CovidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ModelView;
using CovidForm.Models.Shared;
using ModelAccess;

namespace CovidForm.Controllers
{
    public class CovidController : Controller
    {
        // GET: Covid
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            List<Covid_ModelView> List = new List<Covid_ModelView>();
            List = Covid_ModelAccess.GetListAll();
            return PartialView("List", List);
        }

        public ActionResult Create()
        {
            ViewBag.ListJK = Covid_ModelAccess.getJKId();
            return PartialView();
        }

        [HttpPost]
        public ActionResult Create(Covid_ModelView paramModel)
        {
            try
            {
                paramModel.is_delete = false;

                if (ModelState.IsValid)
                {
                    return Json(new
                    {
                        success = Covid_ModelAccess.Insert(paramModel),
                        message = Covid_ModelAccess.Message
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    List<Message> listMessage =
                     Message.GetMessageErrorByModel("paramModel", ModelState);

                    return Json(new
                    {
                        success = false,
                        message = listMessage
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(Int32 paramId)
        {
            ViewBag.ListJK = Covid_ModelAccess.getJKId();
            return PartialView(Covid_ModelAccess.GetDetailsById(paramId));
        }

        [HttpPost]
        public ActionResult Edit(Covid_ModelView paramModel)
        {
            try
            {

                return Json(new
                {
                    success = Covid_ModelAccess.Update(paramModel),
                    message = Covid_ModelAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                },
                JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(Int32 IdDelete)
        {
            return PartialView(Covid_ModelAccess.GetDetailsById(IdDelete));
        }

        [HttpPost]
        public ActionResult Delete(Covid_ModelView paramModelDelete)
        {
            try
            {
                paramModelDelete.is_delete = true;

                return Json(new
                {
                    success = Covid_ModelAccess.Delete(paramModelDelete),
                    message = Covid_ModelAccess.Message
                }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception hasError)
            {
                return Json(new
                {
                    success = false,
                    message = hasError.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

CovidForm/CovidForm/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CovidForm.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CovidForm/CovidForm/Views/Covid/Create.cshtml
@model ModelView.Covid_ModelView

<h6>Deteksi dini Covid-19 bagi civitas akademika UNSIKA</h6>
<hr />
<div class="form-horizontal" style="width:700px">
    <div class="row">
        <div class="form-group col-sm-6">
            <label for="email">Email :</label>
            <input type="text" class="form-control" id="email" />
            <span class="error_form" id="email_error" style="position:fixed"></span>
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="nama">Nama :</label>
            <input type="text" class="form-control" id="nama" />
            @Html.ValidationMessageFor(model => model.nama, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="npm">NPM/NIS :</label>
            <input type="text" class="form-control" id="npm" />
            @Html.ValidationMessageFor(model => model.npm, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="umur">Umur :</label>
            <input type="text" class="form-control" id="umur" />
            @Html.ValidationMessageFor(model => model.umur, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="jk">Jenis Kelamin :</label><br>
            @Html.DropDownListFor(model => model.jk, new SelectList(ViewBag.ListJK, "value", "name"), "--Pilih Jenis Kelamin--", new { @class = "form-control" })
        </div>

        <div class="form-group col-sm-6">
            <label for="telp">Telp :</label>
            <input type="text" class="form-control" id="telp" />
            @Html.ValidationMessageFor(model => model.telp, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="alamat">Alamat Saat Ini :</label>
            <input type="text" class="form-control" id="alamat" />
            @Html.ValidationMessageFor(model => model.alamat, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="asal">Alamat Asal :</label>
            <input type="text" class="form-control" id="asal" />
            @Html.ValidationMessageFor(model => model.asal, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="berada">Saat Ini Berada Di ?</label>
            <input type="text" class="form-control" id="berada" />
            @Html.ValidationMessageFor(model => model.berada, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
<footer>
    <div class="btn-group col-md-offset-10" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-save btn-primary" id="btn_create_save">Kirim</button>
        <input type="button" value="Cancel" title="Cancel" class="btn btn-danger" data-dismiss="modal" />
    </div>
</footer>

CovidForm/CovidForm/Views/Covid/Delete.cshtml
@model ModelView.Covid_ModelView

<div class="modal-body" style="color: #c81912">
    <div class="row">
        <div class="col-md-3"><i class="fas fa-trash" style="display:block; width: 70%; height: 70%; margin: auto"></i></div>
        <div class="col-md-9">
            <h3 style="margin: auto; padding: 10px">Anda yakin ingin menghapus <br />@Html.DisplayFor(model => model.nama)?</h3>
            @Html.HiddenFor(model => Model.id)
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-batal btn-secondary" id="batal" onclick="batalAction(this)">Tidak</button>
    <button type="button" class="btn btn-primary btnKonfirmasiDelete" id="btn_delete" style="background-color:#c81912">Ya</button>
</div>

<script>
    batalAction=(e)=>{
        $("#modalDelete").modal('hide');
    }
</script>

CovidForm/CovidForm/Views/Covid/Edit.cshtml
@model ModelView.Covid_ModelView

@Html.AntiForgeryToken()
<div class="form-horizontal" style="width:700px">
    <div class="row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)
        <div class="form-group col-sm-6">
            <label for="email">Email :</label>
            <input type="text" class="form-control" id="email" value="@Model.email" />
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="nama">Nama :</label>
            <input type="text" class="form-control" id="nama" value="@Model.nama" />
            @Html.ValidationMessageFor(model => model.nama, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="npm">NPM/NIS :</label>
            <input type="text" class="form-control" id="npm" value="@Model.npm" />
            @Html.ValidationMessageFor(model => model.npm, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="umur">Umur :</label>
            <input type="text" class="form-control" id="umur" value="@Model.umur" />
            @Html.ValidationMessageFor(model => model.umur, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="jk">Jenis Kelamin :</label><br>
            @Html.DropDownListFor(model => model.jk, new SelectList(ViewBag.ListJK, "value", "name"), "--Pilih Jenis Kelamin--", new { @class = "form-control" })
        </div>

        <div class="form-group col-sm-6">
            <label for="telp">Telp :</label>
            <input type="text" class="form-control" id="telp" value="@Model.telp" />
            @Html.ValidationMessageFor(model => model.telp, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="alamat">Alamat Saat Ini :</label>
            <input type="text" class="form-control" id="alamat" value="@Model.alamat" />
            @Html.ValidationMessageFor(model => model.alamat, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="asal">Alamat Asal :</label>
            <input type="text" class="form-control" id="asal" value="@Model.asal" />
            @Html.ValidationMessageFor(model => model.asal, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-6">
            <label for="berada">Saat Ini Berada Di ?</label>
            <input type="text" class="form-control" id="berada" value="@Model.berada" />
            @Html.ValidationMessageFor(model => model.berada, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
<footer>
    <div class="btn-group col-md-offset-8" role="group" aria-label="Basic example">
        <input type="button" value="Edit" title="Edit" class="btn btn-primary" id="Edit" />
        <input type="button" value="Cancel" title="Cancel" class="btn btn-danger" data-dismiss="modal" />
    </div>
</footer>

CovidForm/CovidForm/Views/Covid/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="header">
                <h1>List Covid</h1>
            </div>
            &nbsp;
            <button class="btn btn-info" title="Tambah Data" id="btn_create" name="btn_create">
                <span class="nav-icon fas fa-plus" aria-hidden="true"></span>
            </button>
        </div>
        <div class="panel-body">
            <div id="table-list" name="table-list">
                @Html.Partial("List")
            </div>
        </div>
    </div>
</div>

<!-- Model Content -->
<div class="modal fade" id="modal-edit-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabelAdd" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width:700px">
        <!-- Modal Content-->
        <div class="modal-content" style="width:780px">
            <div class="modal-header">
                <!--<button class="close" data-dismiss="modal">&times;</button>-->
                <h3 class="modal-title modal-mn"></h3>
            </div>
            <div class="modal-bind-content" style="margin-top:10px; margin-left:40px; margin-right:40px; margin-bottom:10px">
                <div class="modal-body">
                    <input type="hidden" id="action" value="">
                </div>
            </div>
        </div>
    </div>
</div>

<!--Modal Popup Delete-->
<div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width: 500px">
        <div class="modal-content">
            <div class="modal-header" style="background: #B61111">
                <h3 class="modal-title modal-mn"></h3>
            </div>
            <div class="modal-bind-content" style="margin-top:10px; margin-left:40px; margin-right:40px; margin-bottom:10px">
                <div class="modal-body">

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        var vjs_loading = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"></div></div>';

        $(document).ready(function () {
            ShowList()
        });

        //Method untuk Menampilkan Data
        function ShowList() {
            debugger;
            $("#table-list").html(vjs_loading);

            $.ajax({
                url: '@Url.Action("List", "Covid")',
                type: 'get',
                data: {
                },
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }

        $("#btn_create").click(function () {
            /* setting konfigurasi pop-up / modal */
            $("#modal-edit-form").modal("show"); //memunculkan pop-up
            $(".modal-title").html("FORMULIR DETEKSI DINI(COVID-19)"); //memunculkan title pop-up
            $(".modal-bind-content").html(vjs_loading); //mensetting body menjadi animasi loading

            /* Setting body modal dari view */
            $.ajax({
                url: '@Url.Action("Create","Covid")',
                type: 'get',
                success: function (result) {
                    $(".modal-bind-content").html(result);
                }
            });
        });

        $(document).on("click", "#btn_create_save", function () {
            debugger;
            //Ambil Nilai Pada Form
            var vjs_email = $("#email").val();
            var vjs_name = $("#nama").val();
            var vjs_npm = $("#npm").val();
            var vjs_umur = $("#umur").val();
            var vjs_jk = $("#jk").val();
            var vjs_telp = $("#telp").val();
            var vjs_alamat = $("#alamat").val();
            var vjs_asal = $("#asal").val();
            var vjs_berada = $("#berada").val();

            //Membuat Variabel Json / class dari nilai form
            var item = {
                email: vjs_email,
                nama: vjs_name,
                npm: vjs_npm,
                umur: vjs_umur,
                jk: vjs_jk,
                telp: vjs_telp,
                alamat: vjs_alamat,
                asal: vjs_asal,
                berada: vjs_berada
            };

            $.ajax({
                url: '@Url.Action("Create", "Covid")',
                type: 'post',
                data: { paramModel: item },
                success: function (result) {
                    if (result.success) {
                        alert("Data Berhasil Dikirim");
                        $("#modal-edit-form").modal("hide"); //menutup pop-up
                        ShowList();
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });

        //Popup Edit
        $(document).on("click", ".btn_grid_edit", function () {
            $("#modal-edit-form").modal("show");
            $(".modal-title").html("Update Data");
            $(".modal-bind-content").html(vjs_loading);

            //Membuat variabel tombol edit grid
            var vjs_Id = $(this).attr("data-id");

            $.ajax({
                url: '@Url.Action("Edit","Covid")',
                type: 'get',
                data: { paramId: vjs_Id },
                success: function (result) {
                    $(".modal-bind-content").html(result);
                }
            });
        });

        $(document).on("click", "#Edit", function () {
            debugger;
            //Ambil Nilai Pada Form
            var vjs_Id = $("#id").val();
            var vjs_email = $("#email").val();
            var vjs_name = $("#nama").val();
            var vjs_npm = $("#npm").val();
            var vjs_umur = $("#umur").val();
            var vjs_jk = $("#jk").val();
            var vjs_telp = $("#telp").val();
            var vjs_alamat = $("#alamat").val();
            var vjs_asal = $("#asal").val();
            var vjs_berada = $("#berada").val();

            //Membuat Variabel Json / class dari nilai form
            var itemEdit = {
                id: vjs_Id,
                email: vjs_email,
                nama: vjs_name,
                npm: vjs_npm,
                umur: vjs_umur,
                jk: vjs_jk,
                telp: vjs_telp,
                alamat: vjs_alamat,
                asal: vjs_asal,
                berada: vjs_berada,
                is_delete: false
            };

            $.ajax({
                url: '@Url.Action("Edit", "Covid")',
                type: 'POST',
                data: { paramModel: itemEdit },
                success: function (result) {
                    if (result.success) {
                        alert("Data Berhasil Diedit");
                        $("#modal-edit-form").modal("hide"); //menutup pop-up
                        ShowList();
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });

        //Popup delete
        $(document).on("click", ".btn_grid_delete", function () {
            debugger;
            $("#modalDelete").modal("show");
            $(".modal-title").html("Hapus Data");
            $(".modal-bind-content").html(vjs_loading);

            //Membuat variabel tombol edit grid
            var vjs_id = $(this).attr("data-id");

            $.ajax({
                url: '@Url.Action("Delete","Covid")',
                type: 'get',
                data: { IdDelete: vjs_id },
                success: function (result) {
                    $(".modal-bind-content").html(result);
                }
            });
        });

        $(document).on("click", "#btn_delete", function () {
            var vjs_id = $("#id").val();

            var itemDelete = {
                Id: vjs_id
            }

            $.ajax({
                url: '@Url.Action("Delete", "Covid")',
                type: 'post',
                data: { paramModelDelete: itemDelete },
                success: function (result) {
                    if (result.success) {
                        alert("Data Berhasil Dihapus");
                        $("#modalDelete").modal("hide");
                        ShowList();
                    }
                    else {
                        alert(result.message);
                    }
                }
            });
        });
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
}

CovidForm/CovidForm/Views/Covid/List.cshtml
@model IEnumerable<ModelView.Covid_ModelView>

@{
    ViewBag.Title = "List";
}

<table class="table">
    <tr>
        <th>
            <font size="4" color="#023692">Email</font>
        </th>
        <th>
            <font size="4" color="#023692">Nama</font>
        </th>
        <th>
            <font size="4" color="#023692">NPM/NIS</font>
        </th>
        <th>
            <font size="4" color="#023692">Umur</font>
        </th>
        <th>
            <font size="4" color="#023692">Jenis Kelamin</font>
        </th>
        <th>
            <font size="4" color="#023692">Telp</font>
        </th>
        <th>
            <font size="4" color="#023692">Alamat Saat ini</font>
        </th>
        <th>
            <font size="4" color="#023692">Alamat Asal</font>
        </th>
        <th>
            <font size="4" color="#023692">Keberadaan</font>
        </th>
        <th>
            <font size="4" color="#023692">Action</font>
        </th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nama)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.npm)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.umur)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.jenisKelamin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.telp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.alamat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.asal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.berada)
                </td>
                <td>
                    <button title="Edit" class="btn btn-warning btn_grid_edit" data-id="@item.id">
                        <span class="fa fa-edit" aria-hidden="true">
                        </span>
                    </button>
                    <button title="Delete" class="btn btn-danger btn_grid_delete" data-id="@item.id">
                        <span class="fa fa-trash" aria-hidden="true">
                        </span>
                    </button>
                </td>
            </tr>
        }

    }
</table>

CovidForm/CovidForm/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CovidForm/CovidForm/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CovidForm/CovidForm/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>